# Generated by Django 4.0.5 on 2022-06-20 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('nomProducto', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('nomCategoria', models.CharField(max_length=80, verbose_name='Nombre Categoría')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('porcDesctoSubscriptor', models.IntegerField(verbose_name='Descuento Subscriptor')),
                ('porDesctoOferta', models.IntegerField(verbose_name='Descuento Oferta')),
                ('urlImagenProducto', models.CharField(max_length=300, verbose_name='Imágen Producto')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=80, null=True, verbose_name='Rut')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('urlImagenUsuario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Imágen Usuario')),
                ('esSubscriptor', models.CharField(blank=True, max_length=2, null=True, verbose_name='Es Suscriptor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nroFactura', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro. de factura')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('montoTotal', models.IntegerField(verbose_name='Monto total')),
                ('estadoActual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado actual')),
                ('idProd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.producto', verbose_name='ID de Producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ID de usuario')),
            ],
        ),
    ]
