# Generated by Django 4.0.6 on 2022-07-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('idDetalle', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de detalle factura')),
                ('porcDesctoSubscriptor', models.IntegerField(verbose_name='Descuento Subscriptor')),
                ('porDesctoOferta', models.IntegerField(verbose_name='Descuento Oferta')),
                ('subTotal', models.IntegerField(verbose_name='Sub total')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.perfilusuario')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.producto')),
            ],
        ),
    ]
