# Generated by Django 4.0.6 on 2022-07-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_producto_stock_detallefactura_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.perfilusuario', verbose_name='ID de usuario'),
        ),
    ]
